# Generated by Django 5.2.4 on 2025-10-02 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم الفئة (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الفئة (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='وصف الفئة (عربي)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='وصف الفئة (إنجليزي)')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='أيقونة الفئة')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='لون الفئة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فئة صور تذكارية',
                'verbose_name_plural': 'فئات الصور التذكارية',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='MemoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان الصورة (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الصورة (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='وصف الصورة (عربي)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='وصف الصورة (إنجليزي)')),
                ('image', models.ImageField(upload_to='memory_photos/', verbose_name='الصورة')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='memory_thumbnails/', verbose_name='صورة مصغرة')),
                ('alt_text_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='النص البديل (عربي)')),
                ('alt_text_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='النص البديل (إنجليزي)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='صورة مميزة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.memorycategory', verbose_name='الفئة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'صورة تذكارية',
                'verbose_name_plural': 'الصور التذكارية',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
