# Generated by Django 5.2.4 on 2025-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_memorycategory_memoryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorycategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الفئة'),
        ),
        migrations.AddField(
            model_name='memorycategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='memorycategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الفئة (عربي)'),
        ),
    ]
