# Generated by Django 5.2.4 on 2025-10-02 10:43

from django.db import migrations

def migrate_category_data(apps, schema_editor):
    MemoryCategory = apps.get_model('api', 'MemoryCategory')
    
    for category in MemoryCategory.objects.all():
        # Copy data from old fields to new fields
        category.name = category.name_ar
        category.description = category.description_ar
        category.save()

def reverse_migrate_category_data(apps, schema_editor):
    MemoryCategory = apps.get_model('api', 'MemoryCategory')
    
    for category in MemoryCategory.objects.all():
        # Copy data back from new fields to old fields
        category.name_ar = category.name
        category.description_ar = category.description
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_new_fields_to_memorycategory'),
    ]

    operations = [
        migrations.RunPython(migrate_category_data, reverse_migrate_category_data),
    ]
