# Generated by Django 5.2.4 on 2025-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_migrate_memorycategory_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorycategory',
            options={'ordering': ['name'], 'verbose_name': 'فئة صور تذكارية', 'verbose_name_plural': 'فئات الصور التذكارية'},
        ),
        migrations.RemoveField(
            model_name='memorycategory',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='memorycategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='memorycategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='memorycategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='memorycategory',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='memorycategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='memorycategory',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='memorycategory',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='اسم الفئة'),
            preserve_default=False,
        ),
    ]
