# Generated by Django 5.2.4 on 2025-10-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_old_fields_from_memorycategory'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS api_photoalbum_photos;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS api_photoalbum;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS api_photo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS api_category;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
