# Generated by Django 5.2.4 on 2025-10-02 11:00

from django.db import migrations, models


def check_table_exists(schema_editor, table_name):
    """Check if a table exists in the database"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [table_name])
        return cursor.fetchone()[0]


def safe_remove_fields(apps, schema_editor):
    """Safely remove fields only if tables exist"""
    # Check if tables exist before trying to modify them
    if check_table_exists(schema_editor, 'api_photo'):
        # Tables exist, so we can safely remove fields
        from django.db import connection
        with connection.cursor() as cursor:
            # Remove foreign key constraints and fields if they exist
            try:
                cursor.execute("ALTER TABLE api_photo DROP COLUMN IF EXISTS category_id CASCADE;")
                cursor.execute("ALTER TABLE api_photo DROP COLUMN IF EXISTS uploaded_by_id CASCADE;")
            except:
                pass
    
    if check_table_exists(schema_editor, 'api_photoalbum'):
        from django.db import connection
        with connection.cursor() as cursor:
            try:
                cursor.execute("ALTER TABLE api_photoalbum DROP COLUMN IF EXISTS category_id CASCADE;")
                cursor.execute("ALTER TABLE api_photoalbum DROP COLUMN IF EXISTS cover_photo_id CASCADE;")
            except:
                pass


def safe_delete_tables(apps, schema_editor):
    """Safely delete tables only if they exist"""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS api_photoalbum_photos CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS api_photoalbum CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS api_photo CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS api_category CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20251002_1352'),
    ]

    operations = [
        migrations.RunPython(safe_remove_fields, migrations.RunPython.noop),
        migrations.RunPython(safe_delete_tables, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='memoryphoto',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AlterField(
            model_name='memoryphoto',
            name='title_ar',
            field=models.CharField(max_length=200, verbose_name='عنوان الصورة'),
        ),
    ]
