# Generated by Django 5.2.4 on 2025-10-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_photo_category_remove_photoalbum_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryphoto',
            options={'ordering': ['-created_at'], 'verbose_name': 'صورة تذكارية', 'verbose_name_plural': 'الصور التذكارية'},
        ),
        migrations.RemoveField(
            model_name='memoryphoto',
            name='alt_text_ar',
        ),
        migrations.RemoveField(
            model_name='memoryphoto',
            name='alt_text_en',
        ),
        migrations.RemoveField(
            model_name='memoryphoto',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='memoryphoto',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='memoryphoto',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='memoryphoto',
            name='title_en',
        ),
    ]
