# Generated by Django 5.2.4 on 2025-10-02 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_unwanted_memory_photo_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم فئة اللقاء')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف فئة اللقاء')),
                ('color', models.CharField(default='#10B981', max_length=7, verbose_name='لون الفئة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فئة اللقاءات',
                'verbose_name_plural': 'فئات اللقاءات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان صورة اللقاء')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='وصف صورة اللقاء')),
                ('image', models.ImageField(upload_to='meeting_photos/', verbose_name='صورة اللقاء')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='meeting_thumbnails/', verbose_name='صورة مصغرة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='صورة مميزة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.meetingcategory', verbose_name='فئة اللقاء')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'صورة اللقاء',
                'verbose_name_plural': 'صور اللقاءات',
                'ordering': ['-created_at'],
            },
        ),
    ]
