# Generated by Django 5.2.4 on 2025-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_meetingcategory_meetingphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='المنصب')),
                ('current_workplace', models.CharField(blank=True, max_length=300, null=True, verbose_name='جهة العمل الحالية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='نبذة تعريفية')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='colleague_photos/', verbose_name='الصورة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('promoted', 'وصل لمنصب عالي'), ('deceased', 'متوفى')], default='active', max_length=20, verbose_name='الحالة')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='سنة التخرج')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='الإنجازات')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='معلومات التواصل')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'زميل',
                'verbose_name_plural': 'الزملاء',
                'ordering': ['name'],
            },
        ),
    ]
