# Generated by Django 5.2.4 on 2025-11-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_colleague'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='photos',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PhotoAlbum',
        ),
    ]
