# Generated by Django 5.2.6 on 2025-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_photo_category_remove_photoalbum_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleague',
            name='death_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة الوفاة'),
        ),
        migrations.AddField(
            model_name='colleague',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('son', 'ابن'), ('daughter', 'ابنة'), ('brother', 'أخ'), ('sister', 'أخت'), ('father', 'أب'), ('mother', 'أم'), ('other', 'آخر')], max_length=20, null=True, verbose_name='وصلة القرابة'),
        ),
        migrations.AddField(
            model_name='colleague',
            name='relative_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم قريب له'),
        ),
        migrations.AlterField(
            model_name='colleague',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص'),
        ),
    ]
