# Generated by Django 5.2.6 on 2025-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_deceased_fields_to_colleague'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorycategory',
            options={'ordering': ['-year', 'name'], 'verbose_name': 'فئة صور تذكارية', 'verbose_name_plural': 'فئات الصور التذكارية'},
        ),
        migrations.AddField(
            model_name='memorycategory',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='السنة'),
        ),
    ]
