# Generated by Django 5.2.6 on 2025-11-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_year_to_memory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingcategory',
            options={'ordering': ['-year', 'name'], 'verbose_name': 'فئة اللقاءات', 'verbose_name_plural': 'فئات اللقاءات'},
        ),
        migrations.AddField(
            model_name='meetingcategory',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='السنة'),
        ),
    ]
