# Generated by Django 5.2.4 on 2025-11-14 12:49

from django.db import migrations


def check_table_exists(schema_editor, table_name):
    """Check if a table exists in the database"""
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [table_name])
            result = cursor.fetchone()
            return result and result[0]
        else:
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='table' AND name=?;
            """, [table_name])
            return cursor.fetchone() is not None


def safe_delete_models(apps, schema_editor):
    """Safely delete models only if they exist"""
    # Check if tables exist before trying to delete them
    tables_to_check = ['api_category', 'api_photo', 'api_photoalbum']
    
    for table in tables_to_check:
        if check_table_exists(schema_editor, table):
            try:
                with schema_editor.connection.cursor() as cursor:
                    cursor.execute(f"DROP TABLE IF EXISTS {table} CASCADE;")
            except Exception as e:
                # Tables might have already been deleted in a previous migration
                print(f"Table {table} does not exist or already deleted: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_year_to_meeting_category'),
    ]

    operations = [
        migrations.RunPython(
            safe_delete_models,
            migrations.RunPython.noop,  # No reverse operation
        ),
    ]
