# Generated by Django 5.2.6 on 2025-11-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_performance_indexes'),
        ('api', '0015_remove_photo_category_remove_photoalbum_category_and_more'),
    ]

    operations = [
    ]
