# Generated by Django 5.2.4 on 2025-11-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20251114_1925'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='colleague',
            name='colleague_grad_year_idx',
        ),
        migrations.RemoveField(
            model_name='colleague',
            name='graduation_year',
        ),
    ]
