# Generated by Django 5.2.4 on 2025-11-23 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_colleague_image_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='cover_photo',
        ),
        migrations.RemoveIndex(
            model_name='colleague',
            name='api_colleag_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='colleague',
            name='api_colleag_status_featured_idx',
        ),
        migrations.RemoveIndex(
            model_name='colleague',
            name='api_colleag_grad_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='meetingcategory',
            name='api_meeting_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='meetingcategory',
            name='api_meeting_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='meetingphoto',
            name='api_meetingp_featured_idx',
        ),
        migrations.RemoveIndex(
            model_name='memorycategory',
            name='api_memoryc_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='memorycategory',
            name='api_memoryc_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='memoryphoto',
            name='api_memoryp_featured_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingphoto',
            new_name='meeting_photo_created_idx',
            old_name='api_meetingp_created_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingphoto',
            new_name='meeting_cat_date_idx',
            old_name='api_meetingp_cat_created_idx',
        ),
        migrations.RenameIndex(
            model_name='memoryphoto',
            new_name='memory_photo_created_idx',
            old_name='api_memoryp_created_idx',
        ),
        migrations.RenameIndex(
            model_name='memoryphoto',
            new_name='memory_cat_date_idx',
            old_name='api_memoryp_cat_created_idx',
        ),
        migrations.AlterField(
            model_name='colleague',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='colleague',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='colleague',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('promoted', 'وصل لمنصب عالي'), ('deceased', 'متوفى')], db_index=True, default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='meetingphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='meetingphoto',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='صورة مميزة'),
        ),
        migrations.AlterField(
            model_name='memoryphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='memoryphoto',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='صورة مميزة'),
        ),
        migrations.AddIndex(
            model_name='colleague',
            index=models.Index(fields=['status', 'name'], name='colleague_status_name_idx'),
        ),
        migrations.AddIndex(
            model_name='colleague',
            index=models.Index(fields=['is_featured', 'name'], name='colleague_featured_name_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingphoto',
            index=models.Index(fields=['category', 'is_featured'], name='meeting_cat_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingphoto',
            index=models.Index(fields=['is_featured', '-created_at'], name='meeting_featured_date_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryphoto',
            index=models.Index(fields=['category', 'is_featured'], name='memory_cat_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryphoto',
            index=models.Index(fields=['is_featured', '-created_at'], name='memory_featured_date_idx'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PhotoAlbum',
        ),
    ]
