# Generated by Django 5.2.4 on 2025-11-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_colleague_image_system'),
        ('api', '0019_remove_photo_category_remove_photoalbum_category_and_more'),
    ]

    operations = [
    ]
