# Generated by Django 5.2.4 on 2025-11-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20251123_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcategory',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب'),
        ),
    ]
