# Generated by Django 5.2.4 on 2025-11-28 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_youtube_link_to_meetingcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان الفيديو')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='وصف الفيديو')),
                ('youtube_url', models.URLField(max_length=500, verbose_name='رابط يوتيوب')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='فيديو مميز')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('category', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.meetingcategory', verbose_name='فئة اللقاء')),
            ],
            options={
                'verbose_name': 'فيديو اللقاء',
                'verbose_name_plural': 'فيديوهات اللقاءات',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [
                    models.Index(fields=['category', 'sort_order'], name='meeting_video_cat_sort_idx'),
                    models.Index(fields=['category', '-created_at'], name='meeting_video_cat_date_idx'),
                    models.Index(fields=['is_featured', '-created_at'], name='meeting_video_featured_idx'),
                ],
            },
        ),
    ]
