# Generated by Django 5.2.4 on 2025-11-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_photo_category_remove_photoalbum_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryphoto',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='meetingphoto',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='meetingvideo',
            name='title_ar',
        ),
    ]
