"""
Django settings for college_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must be set in environment variables for production
SECRET_KEY = config('SECRET_KEY', default='django-insecure-yv!kz-43lgp^0789dlq848+epngu$fq=us+y9s4ef=r&+%w#ax')

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True if running on localhost (for local development)
default_debug = 'localhost' in config('ALLOWED_HOSTS', default='localhost,127.0.0.1') or '127.0.0.1' in config('ALLOWED_HOSTS', default='localhost,127.0.0.1')
DEBUG = config('DEBUG', default=default_debug, cast=bool)

# Validate SECRET_KEY in production (AFTER DEBUG is defined)
if not DEBUG and SECRET_KEY == 'django-insecure-yv!kz-43lgp^0789dlq848+epngu$fq=us+y9s4ef=r&+%w#ax':
    import warnings
    warnings.warn(
        "⚠️  SECURITY WARNING: Using default SECRET_KEY in production! "
        "Set SECRET_KEY environment variable immediately.",
        RuntimeWarning,
        stacklevel=2
    )

# Warn if DEBUG is True (helpful for catching misconfigurations)
if DEBUG:
    import warnings
    warnings.warn(
        "⚠️  DEBUG mode is enabled. Do not use in production!",
        RuntimeWarning,
        stacklevel=2
    )

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='kfupm73.cloud,www.kfupm73.cloud,72.61.147.23,localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'https://kfupm73.cloud',
    'https://www.kfupm73.cloud',
    'http://kfupm73.cloud',
    'http://www.kfupm73.cloud',
    'http://72.61.147.23',
    'http://localhost',
    'http://127.0.0.1',
    'http://localhost:8081',
    'http://127.0.0.1:8081',
    'https://localhost',
    'https://127.0.0.1',
]

# CSRF Cookie settings for admin
CSRF_COOKIE_SECURE = not DEBUG  # True in production (HTTPS)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'

# Session settings
SESSION_COOKIE_SECURE = not DEBUG  # True in production (HTTPS)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    # 'django_extensions',  # For HTTPS support with runserver_plus (optional - install with: pip install django-extensions)
    'api',
    'memories',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'college_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        # When custom loaders are defined, APP_DIRS must be False
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # Disable template caching in development to ensure changes are picked up immediately
            'debug': DEBUG,
            # Use non-cached loaders in DEBUG mode to ensure template changes are picked up immediately
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ] if DEBUG else [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'college_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - supports multiple formats
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Support for DATABASE_URL format (Supabase, Heroku, Railway, etc.)
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Fallback to individual settings
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='college_db'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='admin'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings - Allow bulk uploads
DATA_UPLOAD_MAX_NUMBER_FILES = 100  # Allow up to 100 files in a single request
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB - files larger than this go to disk
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB - max size before writing to temp file

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'login': '5/hour',  # Strict limit for login attempts
        'upload': '20/hour',  # Limit for file uploads
    },
    'UNICODE_JSON': True,  # Ensure proper Unicode (Arabic) handling in JSON responses
    'COERCE_DECIMAL_TO_STRING': True,
}

# CORS Configuration for Frontend Integration
# Separate development and production origins for better security

# Always allow localhost origins for local development
localhost_origins = [
    "http://localhost:5173",  # Vite default port
    "http://127.0.0.1:5173",
    "http://localhost:3000",  # Common React dev port
    "http://127.0.0.1:3000",
    "http://localhost:8080",  # Alternative dev port
    "http://127.0.0.1:8080",
    "http://localhost:8081",  # Alternative dev port
    "http://127.0.0.1:8081",
    "https://localhost:8000",  # HTTPS localhost
    "https://127.0.0.1:8000",
]

if DEBUG:
    # Development origins - allow localhost (both HTTP and HTTPS)
    CORS_ALLOWED_ORIGINS = localhost_origins.copy()
else:
    # Production origins - HTTPS ONLY for security
    CORS_ALLOWED_ORIGINS = [
        "https://kfupm73.cloud",    # Production domain (HTTPS)
        "https://www.kfupm73.cloud", # Production domain with www (HTTPS)
    ]
    # Override with environment variable if set
    cors_origins_env = config('CORS_ALLOWED_ORIGINS', default=None)
    if cors_origins_env:
        CORS_ALLOWED_ORIGINS = [s.strip() for s in cors_origins_env.split(',') if s.strip()]
    # Also allow localhost in production if explicitly set (for testing)
    if 'localhost' in ALLOWED_HOSTS or '127.0.0.1' in ALLOWED_HOSTS:
        CORS_ALLOWED_ORIGINS.extend(localhost_origins)

CORS_ALLOW_CREDENTIALS = True

# SECURITY: Never allow all origins in production
CORS_ALLOW_ALL_ORIGINS = False

# Additional CORS headers for Django admin static files
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Security settings for production
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS
    SECURE_HSTS_SECONDS = 31536000  # Enable HSTS for 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    CSRF_TRUSTED_ORIGINS = [
        'https://kfupm73.cloud',
        'https://www.kfupm73.cloud',
    ]
    
    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Suppress HTTPS connection attempt warnings in development
if DEBUG:
    import logging
    # Filter out HTTPS connection attempt warnings from development server
    class HTTPSWarningFilter(logging.Filter):
        def filter(self, record):
            message = str(record.getMessage())
            # Only filter out the specific HTTPS warning messages
            if 'You\'re accessing the development server over HTTPS' in message:
                return False
            if 'Bad HTTP' in message and 'HTTPS' in message:
                return False
            return True
    
    # Apply filter to the server logger
    server_logger = logging.getLogger('django.server')
    server_logger.addFilter(HTTPSWarningFilter())
